#include "proc.h"
#include "process_monitor.h"
#include <ncurses.h> //libreria che e' molto utile per input asincroni su STDIN, per avere un STDIN senza essere bufferizzato, fornire una TUI (text-based user interface),...
